### ISSUE TITLE
Unable to locate a class or view for component [form::switch]

### ISSUE THREAD

**Issue by abduraim** [Okipa/laravel-form-components#12]
Hi there. First, sorry for my english. I have an error when I try to use switch component. Screenshot with error included. Larevel 8. Version of your package 1.0.2. Thanks for your job!

<x:form::switch name="technologies" :group="['tailwind' => 'Tailwind', 'livewire" => 'Livewire']" :checked="livewire"/>

![Снимок экрана 2022-03-05 в 01 39 31](https://user-images.githubusercontent.com/17427874/156851737-90fec5c5-fae5-443c-ad6d-bdf96d46b61a.png)

**Comment by Okipa** [comment]
Hi @abduraim, the way to use toggle switch is : `<x-form::toggle-switch ...`.

I just fixed a few typos in the readme that I missed. Sorry for that !
